apiVersion: apps/v1
kind: Deployment
metadata:
  name: outline
spec:
  selector:
    matchLabels:
      app: outline
  template:
    metadata:
      labels:
        app: outline
    spec:
      containers:
        - name: outline
          image: outlinewiki/outline:0.72.2
          env:
            - name: SECRET_KEY
              value: 5974e36f82085f057223565ac2d0d01427a90248ade611108b4b937672649bd4
            - name: UTILS_SECRET
              value: 8c5a14973325ba56694a99856e6be330812b875e5f683dd37022cf76444774bb
            - name: PORT
              value: '3000'
            - name: URL
              value: 'https://outline.dwbrite.com'
            - name: FORCE_HTTPS
              value: 'false'
            - name: DATABASE_URL
              value: >-
                postgres://outline:cock@outline-wiki-postgresql:5432/outline
            - name: DATABASE_URL_TEST
              value: >-
                postgres://outline:cock@outline-wiki-postgresql:5432/outline-test
            - name: PGSSLMODE
              value: disable
            - name: REDIS_URL
              value: 'redis://outline-wiki-redis-master:6379'
            - name: OIDC_AUTH_URI
              value: >-
                https://keycloak.dwbrite.com/realms/master/protocol/openid-connect/auth
            - name: OIDC_CLIENT_ID
              value: 'outline-wiki'
            - name: OIDC_CLIENT_SECRET
              value: 'AijroobOHjvxjDfolAtzuIJN0Zb2yxS5'
            - name: OIDC_DISPLAY_NAME
              value: 'Login with Keycloak'
            - name: OIDC_SCOPES
              value: 'openid profile email'
            - name: OIDC_TOKEN_URI
              value: >-
                https://keycloak.dwbrite.com/realms/master/protocol/openid-connect/token
            - name: OIDC_USERINFO_URI
              value: >-
                https://keycloak.dwbrite.com/realms/master/protocol/openid-connect/userinfo
            - name: OIDC_USERNAME_CLAIM
              value: preferred_username
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-bucket-access
                  key: access_key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-bucket-access
                  key: secret_key
            - name: AWS_S3_UPLOAD_BUCKET_NAME
              value: "outline"
            - name: AWS_S3_UPLOAD_BUCKET_URL
              value: "https://outline.dwbrite.com:9000/outline"
            - name: AWS_S3_FORCE_PATH_STYLE
              value: "false"
          ports:
            - containerPort: 3000
              protocol: TCP
