# kustomization.yaml in overlays/prod
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

namePrefix: green-


images:
  - name: docker.io/dwbrite/dwbrite-com
    newName: docker.io/dwbrite/dwbrite-com
    newTag: v0.0.3   # Replace with your new tag
  - name: docker.io/dwbrite/media-dwbrite-com
    newName: docker.io/dwbrite/media-dwbrite-com
    newTag: v0.0.3   # Replace with your new tag

patches:
  - target:
      kind: Deployment
      name: website-rs-main
    patch: |-
      - op: replace
        path: /spec/template/metadata/labels/app.kubernetes.io~1instance
        value: green
  - target:
      kind: Deployment
      name: website-rs-media
    patch: |-
      - op: replace
        path: /spec/template/metadata/labels/app.kubernetes.io~1instance
        value: green