apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-rs-main
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: blue

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-rs-media
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: blue
