---
- name: Create cluster SSH key pair
  hosts: localhost
  vars:
    private_key_path: "~/.ssh/clementine.pk"
    public_key_path: "~/.ssh/clementine.pub"
  tasks:
    - name: Generate a new SSH key pair
      openssh_keypair:
        path: "{{ private_key_path }}"
        size: 4096
      register: ssh_key
      when: run_ssh_key_gen

    - name: Save public key
      copy:
        content: "{{ ssh_key.public_key }}"
        dest: "{{ public_key_path }}"
        mode: '0644'
      when: run_ssh_key_gen


- name: Add inter-node SSH keys
  hosts: all_workers
  vars:
    private_key_path: "~/.ssh/clementine.pk"
    public_key_path: "~/.ssh/clementine.pub"
  tasks:
    - name: Add public key to authorized keys
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', public_key_path) }}"

    - name: Enable root SSH login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin yes'
        validate: '/usr/sbin/sshd -t -f %s'
      notify: Restart sshd

  handlers:
    - name: Restart sshd
      service:
        name: sshd
        state: restarted
