---
- name: Create cluster SSH key pair
  hosts: localhost
  vars:
    private_key_path: "~/.ssh/clementine.pk"
    public_key_path: "~/.ssh/clementine.pub"
  tasks:
    - name: Generate a new SSH key pair
      openssh_keypair:
        path: "{{ private_key_path }}"
        size: 4096
      register: ssh_key
      when: run_ssh_key_gen

    - name: Save public key
      copy:
        content: "{{ ssh_key.public_key }}"
        dest: "{{ public_key_path }}"
        mode: '0644'
      when: run_ssh_key_gen

- name: Add inter-node SSH keys
  hosts: all_workers
  vars:
    private_key_path: "~/.ssh/clementine.pk"
    public_key_path: "~/.ssh/clementine.pub"
  tasks:
    - name: Add public key to authorized keys
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', public_key_path) }}"

    - name: Enable root SSH login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin yes'
        validate: '/usr/sbin/sshd -t -f %s'
      notify: Restart sshd

  handlers:
    - name: Restart sshd
      service:
        name: sshd
        state: restarted

- name: Configure HugePages and Kubernetes Nodes
  hosts: all_workers
  become: yes
  tasks:
    - name: Configure sysctl for HugePages (Runtime)
      ansible.builtin.sysctl:
        name: vm.nr_hugepages
        value: "{{hugepages}}"
        state: present
        reload: yes

    - name: Ensure HugePages are configured on reboot
      ansible.builtin.template:
        src: sysctl_hugepages.conf.j2
        dest: "/etc/sysctl.d/99-hugepages.conf"
      when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"
      notify: Reboot message

  handlers:
    - name: Reboot message
      ansible.builtin.debug:
        msg: "Changes were made. You should consider rebooting after this operation."


- name: Enable NVMe Fabrics and NVMe TCP Modules on Kubernetes Nodes
  hosts: all_workers
  become: yes
  tasks:
    - name: Load nvme-fabrics module (Runtime)
      ansible.builtin.modprobe:
        name: nvme-fabrics
        state: present

    - name: Load nvme-tcp module (Runtime)
      ansible.builtin.modprobe:
        name: nvme-tcp
        state: present

    - name: Ensure nvme-fabrics is loaded on reboot
      ansible.builtin.lineinfile:
        path: /etc/modules-load.d/nvme-fabrics.conf
        line: nvme-fabrics
        create: yes

    - name: Ensure nvme-tcp is loaded on reboot
      ansible.builtin.lineinfile:
        path: /etc/modules-load.d/nvme-tcp.conf
        line: nvme-tcp
        create: yes
