---
- name: Fetch kubeconfig from MicroK8s control node
  hosts: novo
  become: yes
  tasks:
    - name: Get kubeconfig from MicroK8s
      command: microk8s config
      register: kubeconfig_raw

- name: Save kubeconfig locally
  hosts: localhost
  tasks:
    - name: Write kubeconfig to local file
      copy:
        content: "{{ hostvars['novo'].kubeconfig_raw.stdout }}"
        dest: ~/.kube/config
        mode: '0600'
