---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lan-cluster-address
  namespace: metallb
spec:
  addresses:
    - 10.11.1.80/28

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: metallb