---
- hosts: localhost
  vars_files:
    - ../vars.yml
  tasks:
    - debug:
        var: clementine_subnet
    - debug:
        var: aster_addr
    - debug:
        var: bernadette_addr
    - debug:
        var: cluster_ip