- name: Create cluster SSH key pair
  hosts: localhost
  vars:
    private_key_path: "~/.ssh/clementine.pk"
    public_key_path:  "~/.ssh/clementine.pub"
  tasks:
    - name: Generate a new SSH key pair
      openssh_keypair:
        path: "{{ private_key_path }}"
        size: 4096
      register: ssh_key

    - name: Save public key
      copy:
        content: "{{ ssh_key.public_key }}"
        dest: "{{ public_key_path }}"
        mode: '0644'