---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deploymentName }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploymentName }}
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: {{ .Values.deploymentName }}
          image: dwbrite/proxy-updater

          env:
            - name: KUBERNETES_SERVICE_HOST
              value: "kubernetes.default.svc"
            - name: KUBERNETES_SERVICE_PORT
              value: "16443"
            - name: SECRET_NAME
              value: {{ .Values.secretName }}
            - name: SECRET_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: PROXY_HOST
              value: {{ .Values.proxyHost }}
            - name: PROXY_USER
              value: {{ .Values.proxyUser }}

      restartPolicy: Always
