{{- range .Values.diskpools }}
---
apiVersion: "openebs.io/v1alpha1"
kind: DiskPool
metadata:
  name: {{ .node }}-diskpool
  namespace: {{ $.Values.namespace }}
spec:
  node: {{ .node }}
  disks: [{{ .disk }}]
{{- end }}
