---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gametank-games
  labels:
    app.kubernetes.io/name: gametank-games
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gametank-games
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gametank-games
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: gametank-games-main
          image: "docker.io/dwbrite/gametank-games:latest"
          env:
            - name: KEYCLOAK_URL
              value: "https://keycloak.dwbrite.com"
            - name: KEYCLOAK_CLIENT_URL
              value: https://keycloak.dwbrite.com/realms/gametank-games/protocol/openid-connect/userinfo
            - name: KEYCLOAK_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-creds
                  key: username
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-creds
                  key: password
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: gametank-games-postgresql
                  key: postgresql-url

          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 41123
              protocol: TCP
