apiVersion: v1
kind: Service
metadata:
  name: gametank-games
spec:
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 41123
  selector:
    app.kubernetes.io/name: gametank-games
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
