apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dwbrite-com
  namespace: istio-system
spec:
  secretName: dwbrite-com-tls
  duration: 2160h0m0s # 90 days
  renewBefore: 360h0m0s # 15 days
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - 'dwbrite.com'
    - '*.dwbrite.com'
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: dwbrite-com-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingress-gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP2
      hosts:
        - "dwbrite.com"
        - "*.dwbrite.com"
      tls:
        httpsRedirect: true

    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "dwbrite.com"
        - "*.dwbrite.com"
      tls:
        mode: SIMPLE
        credentialName: dwbrite-com-tls
    - port:
        number: 9000
        name: minio
        protocol: HTTPS
      hosts:
        - "*.dwbrite.com"
      tls:
        mode: SIMPLE
        credentialName: dwbrite-com-tls

    - port:
        number: 9090
        name: minio-console
        protocol: HTTPS
      hosts:
        - "*.dwbrite.com"
      tls:
        mode: SIMPLE
        credentialName: dwbrite-com-tls
    - port:
        number: 1337
        name: tcp-games
        protocol: TCP
      hosts:
        - "minecraft.dwbrite.com"
    - port:
        number: 25565
        name: tcp-games
        protocol: TCP
      hosts:
        - "mcydb.dwbrite.com"