apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tiny-pizza
  namespace: istio-system
spec:
  secretName: tiny-pizza-tls
  duration: 2160h0m0s # 90 days
  renewBefore: 360h0m0s # 15 days
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - 'tiny.pizza'
    - '*.tiny.pizza'
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tiny-pizza-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingress-gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP2
      hosts:
        - "tiny.pizza"
        - "*.tiny.pizza"
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "tiny.pizza"
        - "*.tiny.pizza"
      tls:
        mode: SIMPLE
        credentialName: tiny-pizza-tls
    - port:
        number: 9000
        name: minio_api
        protocol: HTTP2
      hosts:
        - "*.tiny.pizza"