apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proxy-app
spec:
  source:
    repoURL: https://github.com/dwbrite/firenet
    path: apps/proxy-networking
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: external-proxy
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
