apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs-diskpools
  namespace: {{ .Values.argoNamespace }}
spec:
  project: default
  source:
    repoURL: https://github.com/dwbrite/firenet.git
    path: k8s/apps/openebs/diskpools
    targetRevision: HEAD
    helm:
      values: |
        namespace: {{ .Values.destNamespace }}
        diskpools: {{- toYaml .Values.diskpools | nindent 10 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.destNamespace }}
  syncPolicy:
    automated: {}