apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs-openebs
  namespace: {{ .Values.argoNamespace }}
spec:
  project: default
  source:
    repoURL:  https://openebs.github.io/charts
    targetRevision: {{ .Values.version }}
    chart: openebs
    helm:
      values: |
        image:
          repo: xin3liang

        nodeSelector:
          kubernetes.io/arch: arm64

        csi:
          image:
            registry: docker.io
            repo: xin3liang
          node:
            kubeletDir: /var/snap/microk8s/common/var/lib/kubelet

        mayastor:
          nodeSelector:
            kubernetes.io/arch: arm64

        etcd:
          image:
            repository: xin3liang/bitnami-etcd
            tag: 3.5.1-debian-10-r67
          replicaCount: 1
          volumePermissions:
            image:
              repository: xin3liang/bitnami-shell

        loki-stack:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.destNamespace }}
  syncPolicy:
    automated: {}
