apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs-openebs
  namespace: {{ .Values.argoNamespace }}
spec:
  project: default
  source:
    repoURL:  https://openebs.github.io/charts
    targetRevision: {{ .Values.version }}
    chart: openebs
    helm:
      values: |
        mayastor:
          enabled: true
          io_engine:
            nodeSelector:
              openebs.io/engine: mayastor
              kubernetes.io/arch: arm64
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.destNamespace }}
  syncPolicy:
    automated: {}
