---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: base-dwbrite-com
  labels:
    app.kubernetes.io/name: dwbrite-com
    app.kubernetes.io/instance: base

---
apiVersion: v1
kind: Service
metadata:
  name: dwbrite-com-main
  labels:
    app.kubernetes.io/name: dwbrite-com
    app.kubernetes.io/instance: base
spec:
  ports:
    - port: 80
      targetPort: 41234
  selector:
    app.kubernetes.io/name: dwbrite-com

---
apiVersion: v1
kind: Service
metadata:
  name: dwbrite-com-media
  labels:
    app.kubernetes.io/name: dwbrite-com
    app.kubernetes.io/instance: base
spec:
  ports:
    - port: 80
      targetPort: 41233
  selector:
    app.kubernetes.io/name: dwbrite-com

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-dwbrite-com-main
  labels:
    app.kubernetes.io/name: dwbrite-com
    app.kubernetes.io/instance: base
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dwbrite-com
      app.kubernetes.io/instance: base-main
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dwbrite-com
        app.kubernetes.io/instance: base-main
    spec:
      containers:
        - name: dwbrite-com-main
          image: "docker.io/dwbrite/dwbrite-com:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-dwbrite-com-media
  labels:
    app.kubernetes.io/name: dwbrite-com
    app.kubernetes.io/instance: base
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dwbrite-com
      app.kubernetes.io/instance: base-media
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dwbrite-com
        app.kubernetes.io/instance: base-media
    spec:
      containers:
        - name: dwbrite-com-media
          image: "docker.io/dwbrite/media-dwbrite-com:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
