{{- range .Values.disks }}
apiVersion: openebs.io/v1alpha1
kind: DiskPool
metadata:
  name: datapool-on-{{ .node }}
  namespace: {{ .Release.Namespace }}
spec:
  node: {{ .node }}
  disks: [{{ .disk }}]
---
{{- end }}