preinstall: devin
install machine: (hostname machine) dd cleanup

devin:
    sudo adduser dewbrite
    sudo usermod -aG sudo dewbrite
    sudo su dwbrite
    mkdir ~/.ssh
    chmod 700 ~/.ssh
    cat ./id_rsa.pub >> ~/.ssh/authorized_keys
    chmod 600 ~/.ssh/authorized_keys
    sudo passwd -l ubuntu

hostname machine:
    sudo hostnamectl hostname {{machine}}
    - avahi-set-host-name {{machine}}
    sudo rm /etc/machine-id
    sudo systemd-machine-id-setup

dd:
    sudo bash -c 'cat /dev/mmcblk0 >> /dev/nvme0n1'

cleanup:
    sleep 5
    sudo hostnamectl hostname clementine-proto
    avahi-set-host-name clementine-proto
