# this justfile acts as documentation by example

# secrets.yaml is an ansible vault file, locked by a gitignored .vault_pass.
# said .vault_pass can be found in keepass.

list-inventory:
  ansible-inventory -i inventory.ini --list

# - adds ssh keypair for inter-node communication
# - resizes root partition to fill disk
# initial configuration following manual setup
init-cluster-hardware:
  ansible-playbook -i inventory.ini -l all playbooks/cluster.yaml --vault-password-file .vault_pass --extra-vars '@secrets.yaml'

# modifies vyos configuration to match the config file
network:
  ansible-playbook -i inventory.ini -l network playbooks/network.yaml --vault-password-file .vault_pass --extra-vars '@secrets.yaml'

#
configure-proxies:
  ansible-playbook -i inventory.ini -l proxy playbooks/proxies.yaml --vault-password-file .vault_pass --extra-vars '@secrets.yaml'

edit-secrets:
  ansible-vault edit secrets.yaml --vault-password-file .vault_pass

# runs k0sctl commands on operator machine, applying configuration from config.yaml
create-cluster:
  env SSH_KNOWN_HOSTS=/dev/null k0sctl apply --config config/k0sctl.yaml
  env SSH_KNOWN_HOSTS=/dev/null k0sctl kubeconfig --config config/k0sctl.yaml > ~/.kube/config
  # TODO: fix this - don't start with this bullshit
  kubectl label nodes bernadette storage-capable=true
  kubectl label nodes bernadette openebs.tf.io/engine=mayastor


reset-cluster:
  env SSH_KNOWN_HOSTS=/dev/null k0sctl reset --config config/k0sctl.yaml
