---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.ipAddressPool.name }}
  namespace: {{ .Values.namespace }}
spec:
  addresses:
    - {{ .Values.ipAddressPool.addressRange }}

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .Values.l2advertisement.name }}
  namespace: {{ .Values.namespace }}
